name: FirstJoinPlus
main: me.chaseoes.firstjoinplus.FirstJoinPlus
description: Control all aspects of new players joining for the first time.
author: chaseoes
version: 1.8.1
dev-url: http://dev.bukkit.org/server-mods/firstjoinplus/
website: http://dev.bukkit.org/server-mods/firstjoinplus/
softdepend: [GeoIPTools]
commands:
  firstjoinplus:
    description: FirstJoinPlus command(s).
    aliases: fjp
    usage: /firstjoinplus <reload|setspawn|spawn|items|motd>
permissions:
  firstjoinplus.reload:
    description: Permission to use the /firstjoinplus reload command.
  firstjoinplus.motd:
    description: Permission to use the /firstjoinplus motd command.
  firstjoinplus.setspawn:
    description: Permission to use the /firstjoinplus setspawn command.
  firstjoinplus.items:
    description: Permission to use the /firstjoinplus items command.
  firstjoinplus.spawn:
    description: Permission to use the /firstjoinplus spawn command.
  firstjoinplus.notify:
    description: Players with this permission will hear a sound when a new player joins.
  firstjoinplus.notify-update:
    description: Players with this permission will be notified about updates.